# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartbank_db
spring.datasource.username=root
spring.datasource.password=Naincy@devesh

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Fixed Login Credentials (Spring Security)
spring.security.user.name=Devesh
spring.security.user.password=Devesh123